<?php


$CALENDAR_TABLE = CALENDAR_TABLE;
$CATEGORY_TABLE = CATEGORY_TABLE;
$SETTINGS_TABLE = SETTINGS_TABLE;
$TIMEZONE_TABLE = TIMEZONE_TABLE;			

$defaults = array(

"INSERT INTO $CALENDAR_TABLE (
`calendar_id` ,
`category_id` ,
`calendar_name`
)
VALUES (
'1', '1', 'Sample Calendar'
)",

"INSERT INTO $CATEGORY_TABLE (
`cat_id` ,
`cat_name`
)
VALUES (
'1', 'Sample Category'
)",


"INSERT INTO $SETTINGS_TABLE (`setting_id`, `settings_name`, `settings_value`) VALUES
(1, 'event_publish_mode', 'multi'),
(2, 'default_calendar_view', 'month'),
(3, 'month_view', 'block'),
(4, 'start_week', '1'),
(5, 'weekend', '6'),
(6, 'date_format', '0'),
(7, 'week_format', '0'),
(8, 'url',''),
(9, 'time_intreval', '30'),
(10, 'time_zone', 'America/Toronto'),
(11, 'attachment_dir', 'attachments'),
(12, 'category_enable', '1'),
(13, 'transition_calendar_id', '21'),
(14, 'transition_category_id', '13'),
(15, 'superadmin_email', '$email')",

"INSERT INTO $TIMEZONE_TABLE (`timezone_id`, `tzid`) VALUES
(1, 'Africa/Algiers'),
(2, 'Africa/Luanda'),
(3, 'Africa/Porto-Novo'),
(4, 'Africa/Gaborone'),
(5, 'Africa/Ouagadougou'),
(6, 'Africa/Bujumbura'),
(7, 'Africa/Douala'),
(8, 'Atlantic/Cape_Verde'),
(9, 'Africa/Bangui'),
(10, 'Africa/Ndjamena'),
(11, 'Indian/Comoro'),
(12, 'Africa/Kinshasa'),
(13, 'Africa/Lubumbashi'),
(14, 'Africa/Brazzaville'),
(15, 'Africa/Abidjan'),
(16, 'Africa/Djibouti'),
(17, 'Africa/Cairo'),
(18, 'Africa/Malabo'),
(19, 'Africa/Asmera'),
(20, 'Africa/Addis_Ababa'),
(21, 'Africa/Libreville'),
(22, 'Africa/Banjul'),
(23, 'Africa/Accra'),
(24, 'Africa/Conakry'),
(25, 'Africa/Bissau'),
(26, 'Africa/Nairobi'),
(27, 'Africa/Maseru'),
(28, 'Africa/Monrovia'),
(29, 'Africa/Tripoli'),
(30, 'Antarctica/Casey'),
(31, 'Antarctica/Davis'),
(32, 'Antarctica/Mawson'),
(33, 'Indian/Kerguelen'),
(34, 'Antarctica/DumontDUrville'),
(35, 'Antarctica/Syowa'),
(36, 'Antarctica/Vostok'),
(37, 'Antarctica/Rothera'),
(38, 'Antarctica/Palmer'),
(39, 'Antarctica/McMurdo'),
(40, 'Asia/Kabul'),
(41, 'Asia/Yerevan'),
(42, 'Asia/Baku'),
(43, 'Asia/Bahrain'),
(44, 'Asia/Dhaka'),
(45, 'Asia/Thimphu'),
(46, 'Indian/Chagos'),
(47, 'Asia/Brunei'),
(48, 'Asia/Rangoon'),
(49, 'Asia/Phnom_Penh'),
(50, 'Asia/Harbin'),
(51, 'Asia/Shanghai'),
(52, 'Asia/Chongqing'),
(53, 'Asia/Urumqi'),
(54, 'Asia/Kashgar'),
(55, 'Asia/Hong_Kong'),
(56, 'Asia/Taipei'),
(57, 'Asia/Macau'),
(58, 'Asia/Nicosia'),
(59, 'Asia/Tbilisi'),
(60, 'Asia/Dili'),
(61, 'Asia/Calcutta'),
(62, 'Asia/Jakarta'),
(63, 'Australia/Darwin'),
(64, 'Australia/Perth'),
(65, 'Australia/Brisbane'),
(66, 'Australia/Lindeman'),
(67, 'Australia/Adelaide'),
(68, 'Australia/Hobart'),
(69, 'Australia/Currie'),
(70, 'Australia/Melbourne'),
(71, 'Australia/Sydney'),
(72, 'Australia/Broken_Hill'),
(73, 'Australia/Lord_Howe'),
(74, 'Indian/Christmas'),
(75, 'Pacific/Rarotonga'),
(76, 'Indian/Cocos'),
(77, 'Pacific/Fiji'),
(78, 'Pacific/Gambier'),
(79, 'Pacific/Marquesas'),
(80, 'Pacific/Tahiti'),
(81, 'Pacific/Guam'),
(82, 'Pacific/Tarawa'),
(83, 'Pacific/Enderbury'),
(84, 'Pacific/Kiritimati'),
(85, 'Pacific/Saipan'),
(86, 'Pacific/Majuro'),
(87, 'Pacific/Kwajalein'),
(88, 'Pacific/Truk'),
(89, 'Pacific/Ponape'),
(90, 'Pacific/Kosrae'),
(91, 'Pacific/Nauru'),
(92, 'Pacific/Noumea'),
(93, 'Pacific/Auckland'),
(94, 'Pacific/Chatham'),
(95, 'Pacific/Niue'),
(96, 'Pacific/Norfolk'),
(97, 'Pacific/Palau'),
(98, 'Pacific/Port_Moresby'),
(99, 'Pacific/Pitcairn'),
(100, 'Pacific/Pago_Pago'),
(101, 'Pacific/Apia'),
(102, 'Pacific/Guadalcanal'),
(103, 'Pacific/Fakaofo'),
(104, 'Pacific/Tongatapu'),
(105, 'Pacific/Funafuti'),
(106, 'Pacific/Johnston'),
(107, 'Pacific/Midway'),
(108, 'Pacific/Wake'),
(109, 'Pacific/Efate'),
(110, 'Pacific/Wallis'),
(111, 'Etc/GMT'),
(112, 'Etc/UTC'),
(113, 'Etc/UCT'),
(114, 'Etc/GMT-14'),
(115, 'Etc/GMT-13'),
(116, 'Etc/GMT-12'),
(117, 'Etc/GMT-11'),
(118, 'Etc/GMT-10'),
(119, 'Etc/GMT-9'),
(120, 'Etc/GMT-8'),
(121, 'Etc/GMT-7'),
(122, 'Etc/GMT-6'),
(123, 'Etc/GMT-5'),
(124, 'Etc/GMT-4'),
(125, 'Etc/GMT-3'),
(126, 'Etc/GMT-2'),
(127, 'Etc/GMT-1'),
(128, 'Etc/GMT+1'),
(129, 'Etc/GMT+2'),
(130, 'Etc/GMT+3'),
(131, 'Etc/GMT+4'),
(132, 'Etc/GMT+5'),
(133, 'Etc/GMT+6'),
(134, 'Etc/GMT+7'),
(135, 'Etc/GMT+8'),
(136, 'Etc/GMT+9'),
(137, 'Etc/GMT+10'),
(138, 'Etc/GMT+11'),
(139, 'Etc/GMT+12'),
(140, 'Europe/London'),
(141, 'Europe/Dublin'),
(142, 'WET'),
(143, 'CET'),
(144, 'MET'),
(145, 'EET'),
(146, 'Europe/Tirane'),
(147, 'Europe/Andorra'),
(148, 'Europe/Vienna'),
(149, 'Europe/Minsk'),
(150, 'Europe/Brussels'),
(151, 'Europe/Sofia'),
(152, 'Europe/Prague'),
(153, 'Europe/Copenhagen'),
(154, 'Atlantic/Faeroe'),
(155, 'America/Danmarkshavn'),
(156, 'America/Scoresbysund'),
(157, 'America/Godthab'),
(158, 'America/Thule'),
(159, 'Europe/Tallinn'),
(160, 'Europe/Helsinki'),
(161, 'Europe/Paris'),
(162, 'Factory'),
(163, 'EST'),
(164, 'MST'),
(165, 'HST'),
(166, 'EST5EDT'),
(167, 'CST6CDT'),
(168, 'MST7MDT'),
(169, 'PST8PDT'),
(170, 'America/New_York'),
(171, 'America/Chicago'),
(172, 'America/North_Dakota/Center'),
(173, 'America/North_Dakota/New_Salem'),
(174, 'America/Denver'),
(175, 'America/Los_Angeles'),
(176, 'America/Juneau'),
(177, 'America/Yakutat'),
(178, 'America/Anchorage'),
(179, 'America/Nome'),
(180, 'America/Adak'),
(181, 'Pacific/Honolulu'),
(182, 'America/Phoenix'),
(183, 'America/Boise'),
(184, 'America/Indiana/Indianapolis'),
(185, 'America/Indiana/Marengo'),
(186, 'America/Indiana/Vincennes'),
(187, 'America/Indiana/Petersburg'),
(188, 'America/Indiana/Knox'),
(189, 'America/Indiana/Vevay'),
(190, 'America/Kentucky/Louisville'),
(191, 'America/Kentucky/Monticello'),
(192, 'America/Detroit'),
(193, 'America/Menominee'),
(194, 'America/St_Johns'),
(195, 'America/Goose_Bay'),
(196, 'America/Halifax'),
(197, 'America/Glace_Bay'),
(198, 'America/Moncton'),
(199, 'America/Blanc-Sablon'),
(200, 'America/Montreal'),
(201, 'America/Toronto'),
(202, 'America/Thunder_Bay'),
(203, 'America/Nipigon'),
(204, 'America/Rainy_River'),
(205, 'America/Atikokan'),
(206, 'America/Winnipeg'),
(207, 'America/Regina'),
(208, 'America/Swift_Current'),
(209, 'America/Edmonton'),
(210, 'America/Vancouver'),
(211, 'America/Dawson_Creek'),
(212, 'America/Pangnirtung'),
(213, 'America/Iqaluit'),
(214, 'America/Rankin_Inlet'),
(215, 'America/Cambridge_Bay'),
(216, 'America/Yellowknife'),
(217, 'America/Inuvik'),
(218, 'America/Whitehorse'),
(219, 'America/Dawson'),
(220, 'America/Cancun'),
(221, 'America/Merida'),
(222, 'America/Monterrey'),
(223, 'America/Mexico_City'),
(224, 'America/Chihuahua'),
(225, 'America/Hermosillo'),
(226, 'America/Mazatlan'),
(227, 'America/Tijuana'),
(228, 'America/Anguilla'),
(229, 'America/Antigua'),
(230, 'America/Nassau'),
(231, 'America/Barbados'),
(232, 'America/Belize'),
(233, 'Atlantic/Bermuda'),
(234, 'America/Cayman'),
(235, 'America/Costa_Rica'),
(236, 'America/Havana'),
(237, 'America/Dominica'),
(238, 'America/Santo_Domingo'),
(239, 'America/El_Salvador'),
(240, 'America/Grenada'),
(241, 'America/Guadeloupe'),
(242, 'America/Guatemala'),
(243, 'America/Port-au-Prince'),
(244, 'America/Tegucigalpa'),
(245, 'America/Jamaica'),
(246, 'America/Martinique'),
(247, 'America/Montserrat'),
(248, 'America/Managua'),
(249, 'America/Panama'),
(250, 'America/Puerto_Rico'),
(251, 'America/St_Kitts'),
(252, 'America/St_Lucia'),
(253, 'America/Miquelon'),
(254, 'America/St_Vincent'),
(255, 'America/Grand_Turk'),
(256, 'America/Tortola'),
(257, 'America/St_Thomas'),
(258, 'Asia/Riyadh87'),
(259, 'Asia/Riyadh88'),
(260, 'Asia/Riyadh89'),
(261, 'America/Argentina/Buenos_Aires'),
(262, 'America/Argentina/Cordoba'),
(263, 'America/Argentina/Tucuman'),
(264, 'America/Argentina/La_Rioja'),
(265, 'America/Argentina/San_Juan'),
(266, 'America/Argentina/Jujuy'),
(267, 'America/Argentina/Catamarca'),
(268, 'America/Argentina/Mendoza'),
(269, 'America/Argentina/Rio_Gallegos'),
(270, 'America/Argentina/Ushuaia'),
(271, 'America/Aruba'),
(272, 'America/La_Paz'),
(273, 'America/Noronha'),
(274, 'America/Belem'),
(275, 'America/Fortaleza'),
(276, 'America/Recife'),
(277, 'America/Araguaina'),
(278, 'America/Maceio'),
(279, 'America/Bahia'),
(280, 'America/Sao_Paulo'),
(281, 'America/Campo_Grande'),
(282, 'America/Cuiaba'),
(283, 'America/Porto_Velho'),
(284, 'America/Boa_Vista'),
(285, 'America/Manaus'),
(286, 'America/Eirunepe'),
(287, 'America/Rio_Branco'),
(288, 'America/Santiago'),
(289, 'Pacific/Easter'),
(290, 'America/Bogota'),
(291, 'America/Curacao'),
(292, 'America/Guayaquil'),
(293, 'Pacific/Galapagos'),
(294, 'Atlantic/Stanley'),
(295, 'America/Cayenne'),
(296, 'America/Guyana')");




?>